[package]
name = "interpreter-lox"
version = "0.1.0"
authors = ["Binoy Jayan <binoyjayan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.1"
